---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{.SRIOVMutatingWebhookName}}
  namespace: {{.Namespace}}
  annotations:
    {{if and (not .CaBundle) (eq .ClusterType "openshift") }}
    service.beta.openshift.io/inject-cabundle: "true"
    {{else if and (not .CaBundle) (eq .ClusterType "kubernetes") }}
    cert-manager.io/inject-ca-from: {{.Namespace}}/operator-webhook-service
    {{end}}
webhooks:
  - name: operator-webhook.sriovnetwork.openshift.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: operator-webhook-service
        namespace: {{.Namespace}}
        path: "/mutating-custom-resource"
      {{if .CaBundle}}
      caBundle: "{{.CaBundle}}"
      {{end}}
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["sriovnetwork.openshift.io"]
        apiVersions: ["v1"]
        resources: ["sriovnetworknodepolicies"]

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{.SRIOVMutatingWebhookName}}
  namespace: {{.Namespace}}
  annotations:
    {{if and (not .CaBundle) (eq .ClusterType "openshift") }}
    service.beta.openshift.io/inject-cabundle: "true"
    {{else if and (not .CaBundle) (eq .ClusterType "kubernetes") }}
    cert-manager.io/inject-ca-from: {{.Namespace}}/operator-webhook-service
    {{end}}
webhooks:
  - name: operator-webhook.sriovnetwork.openshift.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: operator-webhook-service
        namespace: {{.Namespace}}
        path: "/validating-custom-resource"
      {{if .CaBundle}}
      caBundle: "{{.CaBundle}}"
      {{end}}
    rules:
      - operations: [ "CREATE", "UPDATE", "DELETE" ]
        apiGroups: ["sriovnetwork.openshift.io"]
        apiVersions: ["v1"]
        resources: ["sriovnetworknodepolicies"]
