---
apiVersion: v1
kind: Service
metadata:
  name: network-resources-injector-service
  namespace: {{.Namespace}}
  annotations:
    {{if eq .ClusterType "openshift"}}
    service.alpha.openshift.io/serving-cert-secret-name: network-resources-injector-service
    {{end}}
spec:
  ports:
  - port: 443
    targetPort: 6443
  selector:
    app: network-resources-injector
