---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{.SRIOVMutatingWebhookName}}
  namespace: {{.Namespace}}
  annotations:
    {{if and (not .CaBundle) (eq .ClusterType "openshift") }}
    service.beta.openshift.io/inject-cabundle: "true"
    {{else if and (not .CaBundle) (eq .ClusterType "kubernetes") }}
    cert-manager.io/inject-ca-from: {{.Namespace}}/network-resources-injector-service
    {{end}}
webhooks:
  - name: network-resources-injector-config.k8s.io
    clientConfig:
      service:
        name: network-resources-injector-service
        namespace: {{.Namespace}}
        path: "/mutate"
      {{if .CaBundle}}
      caBundle: "{{.CaBundle}}"
      {{end}}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
